name: "Test Node Project"
description: "Install dependencies and run npm test"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: "20"

    - run: npm ci
      shell: bash

    - run: npm test
      shell: bash
